version: "3.9"
# no windows instalar do docker desktop
# depois, deve-se criar o volume com o comando abaixo:
# docker volume create --name=sql-vol
# para rodar, na pasta onde está esse arquivo, rodar:
# docker-compose up
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "P@ss@0rd!!!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - "sql-vol:/var/opt/mssql"
volumes:
    sql-vol:
        external: true